package compilator.enums;

public enum EErrorCode {
    ERROR_ASSIGMENT_VARIABLE_NOT_EXISTS(1),
    ERROR_CONSTANT_ASSIGMENT(2),
    ERROR_INVALID_PARAMETERS_COUNT(3),
    ERROR_METHOD_ALREADY_EXISTS(4),
    ERROR_METHOD_NOT_EXISTS(5),
    ERROR_MISMATCH_EXPRESSION_RESULT(6),
    ERROR_MISMATCH_METHOD_CALL_RETURN(7),
    ERROR_MISMATCH_TYPES_EXPRESSION(8),
    ERROR_MISMATCH_TYPES_VARIABLE(9),
    ERROR_SWITCH_MULTIPLE_DEFAULT_BLOCK(10),
    ERROR_VARIABLE_ALREADY_EXISTS(11),
    ERROR_VARIABLE_NOT_EXISTS(12),
    ERROR_VOID_METHOD_EXPRESSION(13),
    ERROR_MISMATCH_METHOD_AND_CALL_PARAMETER_RETURN_TYPE(14),
    ERROR_LOADING_INPUT_FILE(15),
    ERROR_ANTLR_PROCESS(16),
    ERROR_UNKNOWN(17),
    ERROR_INVALID_USE(18),
    ERROR_INVALID_OUTPUT_FILE(19),
    ERROR_ARITHMETIC(20);

    private int code;

    EErrorCode(int code) {
        this.code = code;
    }

    public int getCode() {
        return this.code;
    }
}
